DROP DATABASE IF EXISTS :"DB_NAME";

CREATE DATABASE :"DB_NAME" WITH OWNER :"DB_OWNER" --
    ENCODING 'UTF8' --
    LOCALE_PROVIDER 'icu' --
    ICU_LOCALE 'sv-SE' --
    TEMPLATE template0;

REVOKE ALL ON DATABASE :"DB_NAME" FROM PUBLIC;
