name: Backstage / Verify Pull Request

on:
  pull_request:
    paths:
      - "components/api/backstage/**"

defaults:
  run:
    working-directory: components/api/backstage

jobs:
  build:
    name: "Test and Build"
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "gradle"

      - run: ./gradlew build
